#!/bin/bash
# Description: This helper script will bring up Timesketch, Kibana (separate) and Plaso dockerised versions for rapid deployment. Further, it will set up InsaneTechnologies elastic pipelines so that relevant embedded fields can be extracted and mapped to fields in ES.
# Tested on Ubuntu 22.04 LTS Server Edition
# Created by David Terrey
#
# Usage: sudo ./tsplaso_docker_install.sh
#


# CONSTANTS
# ---------------------------------------
#Setting default user creds
USER1_NAME=dfir
USER1_PASSWORD=admin
# ---------------------------------------

# Install Docker
sudo apt install curl -y
sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --batch --yes --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
sudo echo \
"deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
$(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

# Install all pre-required Linux packages
sudo apt-get update
sudo apt-get install apt-transport-https ca-certificates curl gnupg lsb-release cargo unzip unrar docker.io python3-pip expect docker-compose docker-compose-plugin -y

# Install Portainer for easier container management
sudo systemctl start docker
sudo systemctl enable docker
sudo docker pull portainer/portainer-ce:latest
sudo docker run -d -p 9000:9000 --restart always -v /var/run/docker.sock:/var/run/docker.sock portainer/portainer-ce:latest

Go to localhost:9000 and create an administrator account.

# Download and install Timesketch
sudo curl -s -O https://raw.githubusercontent.com/google/timesketch/master/contrib/deploy_timesketch.sh
sudo chmod 755 deploy_timesketch.sh
sudo mkdir /opt/timesketch
sudo chmod 755 -R /opt/timesketch
sudo mv deploy_timesketch.sh /opt/timesketch
cd /opt/timesketch
sudo ./deploy_timesketch.sh

sudo mkdir /cases
sudo mkdir /data
sudo mkdir /cases/plaso
sudo mkdir /cases/processor
sudo mkdir /cases/evtxproc
sudo mkdir /cases/processor/hashes
sudo mkdir /cases/processor/logfile
sudo mkdir /cases/malware/
sudo mkdir /cases/malware/hashes
sudo mkdir /cases/malware/logfile

sudo chmod -R 777 /cases
sudo chmod -R 777 /data


# Native Install Commented Out
sudo add-apt-repository universe -y
sudo add-apt-repository ppa:gift/stable -y
sudo apt-get update
sudo apt-get install plaso-tools -y

# Ubuntu 24.04 LTS
sudo add-apt-repository universe -y
sudo add-apt-repository ppa:gift/testing
sudo apt update
sudo apt-get install plaso-tools -y


# Install Timesketch import client to assist with larger plaso uploads
sudo pip3 install timesketch-import-client
pip3 install timesketch-import-client

# Download the latest tags file from dterrey forked repo
sudo mkdir /opt/timesketch/etc
sudo mkdir /opt/timesketch/etc/timesketch
sudo wget -Nq https://raw.githubusercontent.com/dterrey/AllthingsTimesketch/master/tags.yaml -O /opt/timesketch/etc/timesketch/tags.yaml


# Install Hayabusa
sudo mkdir /opt/hayabusa
sudo chmod 777 -R /opt/hayabusa
cd /opt/hayabusa/
sudo wget https://github.com/Yamato-Security/hayabusa/releases/download/v2.16.0/hayabusa-2.16.0-all-platforms.zip
sudo unzip hayabusa-2.16.0-all-platforms.zip
sudo chmod 777 -R /opt/
sudo mv /opt/hayabusa/hayabusa-2.16.0-lin-x64-musl /opt/hayabusa/hayabusa
sudo chmod +x /opt/hayabusa/hayabusa

# Install Capa
sudo mkdir /opt/capa
sudo chmod 777 -R /opt/capa
cd /opt/capa/
sudo wget https://github.com/mandiant/capa/releases/download/v7.0.1/capa-v7.0.1-linux.zip
sudo unzip capa-v7.0.1-linux.zip
sudo chmod 777 -R /opt/
sudo chmod +x /opt/capa

# Install Chainsaw
cd /opt/
sudo wget https://github.com/WithSecureLabs/chainsaw/releases/download/v2.9.0/chainsaw_all_platforms+rules.zip
sudo unzip chainsaw_all_platforms+rules.zip
sudo mv /opt/chainsaw/chainsaw_x86_64-unknown-linux-gnu /opt/chainsaw/chainsaw
sudo chmod 777 -R /opt/
sudo chmod +x /opt/chainsaw/chainsaw

# Install ClamAV
sudo apt install clamav -y
sudo mkdir /cases/malware/results
sudo chmod 777 -R /opt/

# Download the loop.sh file for the plaso container
sudo wget -Nq https://raw.githubusercontent.com/dterrey/DFIR_NodeRED/master/loop.sh -O /opt/timesketch/loop.sh

# Create the first user account
sudo docker-compose exec timesketch-web tsctl create-user dfir --password admin

# Install Node-Red
# Download the script
curl -sL https://raw.githubusercontent.com/node-red/linux-installers/master/deb/update-nodejs-and-nodered > /tmp/update_script.sh

# Execute the downloaded script
bash /tmp/update_script.sh

sudo systemctl enable nodered.service
sudo systemctl start nodered.service

#Increase the CSRF token time limit
# OLD --> sudo echo -e '\nWTF_CSRF_TIME_LIMIT = 3600' >> /opt/timesketch/etc/timesketch/timesketch.conf
sudo sh -c "echo -e '\nWTF_CSRF_TIME_LIMIT = 3600' >> /opt/timesketch/timesketch/etc/timesketch/timesketch.conf"



"******************************************************************************************"
printf "To Access Node-Red: localhost:1880 \n"
printf "To Access Timesketch: https://localhost \n"
printf "To Access Portainer via IP:9000 \n"
printf "For KAPE Collection to work with Elastic - SOF ELK is required and to be running on specific ip \n"
echo "*****************************************************************************************\n"
